### ISSUE TITLE
hackercouch.com shows 404

### ISSUE THREAD

**Issue by dhanvi** [hackercouch/hackercouch#1]

**Comment by captn3m0** [comment]
Isn't launched yet. I need to make a few more changes before adding the CNAME file.

**Comment by dcht00** [comment]
Following this!

Also see (and please update): http://totalism.org/alike - an overview of hackerbases, nomadbases, eco villages, and other stuff.

**Comment by captn3m0** [comment]
This is finally live :shipit:
