### ISSUE TITLE
Kudos

### ISSUE THREAD

**Issue by simison** [hackercouch/hackercouch#10]
I feel like the original would serve some kudos at readme, what do you think? :-)

https://github.com/jancborchardt/hackercouch

**Comment by captn3m0** [comment]
Yup, totally makes sense. Will add asap :+1:

**Comment by captn3m0** [comment]
Added links to the readme and a new /related.html page as well.

Thanks!

**Comment by simison** [comment]
Thanks @captn3m0!

FYI, @jancborchardt: https://github.com/captn3m0/hackercouch/commit/0e823fd91630cccbdcd14e1711f1bb6d8ff81ecc

**Comment by jancborchardt** [comment]
Thanks homies! :) Always good to give and receive credit. And good to see the Hackercouch spirit being developed further!
