### ISSUE TITLE
Marking unavailability?

### ISSUE THREAD

**Issue by chreekat** [hackercouch/hackercouch#109]
I actually got a request through Hackercouch! Unfortunately I am 10 time zones away from the location listed in my profile. Oops.

I propose we agree on a standard for marking a profile unavailable. Create a subdirectory? Symlinks like Apache? Or append ".unavailable" to the profile markdown file?

**Comment by chreekat** [comment]
Or the most obvious answer, a new field in the markdown file itself? But I'd rather use the filesystem. I'd also rather not have any extra logic; simply put the file somewhere (agreed-upon) where it won't be picked up by the system so it doesn't show up on the site.

**Comment by simison** [comment]
Just like you forgot to mark yourself unavailable, people would probably forgot to mark themself available again. :-) How about "availability" field where once could update about future trips, e.g.:

`availability: Traveling this summer but back by Sep 1st`

We got a few couch-removals already, what do you think about removing the whole profile for unavailability?

**Comment by chreekat** [comment]
Agreed about forgetting to mark re-available :)

Deleting is maybe best. I thought it would be nice to keep the file around for reference, but otoh there's something pleasing about the idea of using `git revert` to mark one's self available again.

**Comment by chreekat** [comment]
I'm +0 on `'availability'`. I would use it, but I don't think it is necessarily useful information or worth implementing. Better to spend time on Trustroots.

**Comment by simison** [comment]
> Better to spend time on Trustroots. 

:-D Aye! This will work real soon: https://www.trustroots.org/?tribe=hackers

> Deleting is maybe best. I thought it would be nice to keep the file around for reference, but otoh there's something pleasing about the idea of using git revert to mark one's self available again.

Wanna write a quick _howto_? https://github.com/hackercouch/hackercouch/edit/master/add.md
