### ISSUE TITLE
Fields missing in the JSON API

### ISSUE THREAD

**Issue by ArionMiles** [hackercouch/hackercouch#204]
I am trying to build an alternative UI for it by making use of your JSON APIs and I'm seeing some discrepancies in the data returned by the JSON API and what's actually on the site. 

1. The `content` field on `https://hackercouch.com/couches.json` returns the same string for all couches, to get the content specific to each hacker, I have to query their particular couch at `/couches/<hackerName>`

2. The social links on `/couches.json` and `/couches/<hackerName>` do not list all the social media handles

For example: 
https://hackercouch.com/couches/NicolasFrancaX.html
and https://hackercouch.com/couches/NicolasFrancaX.json

as you can see, the facebook, twitter and website fields are missing from the API

**Comment by captn3m0** [comment]
The `content` parameter doesn't show up locally. Not sure what's the difference here between my local and CI environment. Investigating

**Comment by ArionMiles** [comment]
Thanks for fixing the content parameter! 

Though the social links are still missing in the JSON endpoints apart from email and github.
