### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by jancborchardt** [hackercouch/hackercouch#26]
Yo @captn3m0 :) since you used the concept of https://github.com/jancborchardt/hackercouch and push it forward, I’d be cool with you using the logo as well:
![](https://raw.githubusercontent.com/jancborchardt/hackercouch/master/hackercouch.png)
(SVG source in the repo)

**Comment by captn3m0** [comment]
Thats a cool logo. Thanks. I'll add it to the favicon soon and @chettyarun can incorporate it into the design when he works on #7.

**Comment by simison** [comment]
BTW @jancborchardt wanna hack more on this repo? Let us know if you'd need push rights.

**Comment by jancborchardt** [comment]
Sure. I’ll add the favicon and logo tomorrow when I’m on a flight or otherwise have time.

**Comment by simison** [comment]
Super. @captn3m0 wanna give commit rights for Jan? :-)

**Comment by captn3m0** [comment]
Gave commit rights to @jancborchardt and @chettyarun. The latter primarily so I can assign him tickets.

**Comment by simison** [comment]
This is going in with #77
