### ISSUE TITLE
Add gravatar

### ISSUE THREAD

**Issue by abhshkdz** [hackercouch/hackercouch#32]
It might be a good idea to add user images via gravatar?

**Comment by captn3m0** [comment]
Yes, somebody suggested it in a different thread as well. Does it make sense to have it in homepage as well?

Also, another similar point on formatting: Should I use `name` in the home page listing (It currently uses nicks)?

**Comment by abhshkdz** [comment]
Looking at how the list is growing, the homepage at least needs some sort of location-based filtering/search. I'm okay with or without images on homepage. Nicks look fine to me on homepage.

**Comment by ppaeps** [comment]
On 2015-12-01 00:16:18 (+0530), Abhishek Das notifications@github.com 
wrote:

> Looking at how the list is growing, the homepage at least needs some 
> sort of location-based filtering/search.

Or a shell script wrapper around grep in the repository.  I may have 
inadvertently started hacking one up this afternoon.  I'll share a patch 
when it's more complete than `exec grep "$@"`.

:)

It's _hacker_couch, right?  Surely we're a lot more comfortable 
searching in our terminals than in our web clients.

## 

Philip Paeps
Senior Reality Engineer
Ministry of Information

**Comment by Akeru** [comment]
@abhshkdz Gravatars and sorting / filtering are already discussed in #7 as I did not want open multiple issues for the website design.

**Comment by abhshkdz** [comment]
@Akeru My bad. Let's continue the discussion there. Closing this.
