### ISSUE TITLE
Add chat

### ISSUE THREAD

**Issue by simison** [hackercouch/hackercouch#37]
@pierreozoux offered to host [Rocket chat](https://rocket.chat/) instance at his [IndieHosters](https://indiehosters.net/) servers for free.

We already have [#hackercouch](irc://irc.freenode.net/hackercouch) at Freenode, but it's rather quiet due we're all on/off randomly at different timezones and IRC isn't as popular as it used to be in 90's. :-) It's also possible to link these two so it wouldn't matter if you'd use the channel via Rocket or IRC.

Could be hosted at chat.hackercouch.com

Whaddyathink?

---

Edit, Pierre already had an email exhange with @captn3m0 :

> Nemo:
> I think I'll add a link to freenode #hackercouch for now, and
> maybe move to chat.hackercouch.com if it gets popular.
> 
> I'll hop on to the freenode channel soon.
> 
> > > Nemo:
> > > I hadn't given much thought to chat itself. I could
> > > point it sure, but even #hackercouch on freenode would
> > > be fine, I think.
> > 
> > Pierre:
> > It is already created, but not much happening there lately
> > 
> > > Nemo:
> > > Are there any discussions on #hackercouch? There is
> > > also the option of gitter.im (since we have a github
> > > project).
> > 
> > Pierre:
> > Arf, no free software :) Rocket.Chat is :)
> > 
> > > > Pierre:
> > > > Hi!
> > > > 
> > > > We noticed you created hackercouch.com, nice :)
> > > > 
> > > > With Mikael, we are on the irc #hackercouch, and we
> > > > though that a webchat would be nice. I thought about
> > > > hosting rocket.chat, and we have yet to see how to
> > > > connect it to IRC.
> > > > 
> > > > Would you mind pointing chat.hackercouch.com to my
> > > > servers? (If you like the idea, I'll send you the
> > > > procedure)
> > > > 
> > > > All the best!
> > > > 
> > > > Pierre

**Comment by captn3m0** [comment]
Thanks for the reminder. 

/me goes and joines #hackercouch

**Comment by simison** [comment]
BTW `chat.hackercouch.com` could redirect to https://webchat.freenode.net/?channels=hackercouch for now?

**Comment by captn3m0** [comment]
Sounds good, I'll setup the redirect.

Speaking of chat, who has ops on the irc channel? We should get the topic changed to point to the new site.

**Comment by captn3m0** [comment]
Redirect setup using lightsaber.captnemo.in and working. We could change it to hackercouch.com/chat.html later perhaps where we can add instructions on joining the channel maybe

But for now, this feels good enough.
