### ISSUE TITLE
Link to other hospex networks

### ISSUE THREAD

**Issue by simison** [hackercouch/hackercouch#38]
Add profile links to the most popular ones:
- [Couchsurfing](https://www.couchsurfing.com/) (`https://www.couchsurfing.com/people/USERNAME`)
- [BeWelcome](http://bewelcome.org/) (`http://www.bewelcome.org/members/USERNAME`, note http)
- [Warmshowers](https://www.warmshowers.org/) (`https://www.warmshowers.org/user/NUMERIC-USER-ID`)
- [Trustroots](https://www.trustroots.org/) (`https://www.trustroots.org/profile/USERNAME`)

http://ideas.trustroots.org/comparison-of-hospitality-exchange-platforms/

Icons:
- SVG for TR: https://github.com/Trustroots/trustroots/blob/master/modules/core/client/img/tree-white.svg
- PNG icons for the rest: https://github.com/Trustroots/trustroots/tree/master/modules/core/client/img/external

**Comment by captn3m0** [comment]
Just added you to the repo collaborators, btw.

That comparison link is really helpful in thinking of possible features and ideas.

**Comment by simison** [comment]
:+1: Thanks!

If you think adding these links to profiles is a good idea, I could try to tackle it and send a PR.

**Comment by captn3m0** [comment]
Yes, I think having these links is a good idea, but we need to tackle the identity theft issue where someone might just link to a different profile.

You can start working on it for sure.

**Comment by simison** [comment]
There's pretty much no other way for identity theft except oAuth. That won't be possible with CS for sure, BW possibly but will take a long time, with TR probably within 6 months.

Would that work with Jekyll pages — no idea.

**Comment by captn3m0** [comment]
There is a way, by using published proofs on your profile pages. Basically, your hackercouch profile and other profile must share a common sha256 hash, generated at random. (It goes in your about description).

This was how many apps were verifying hacker news identities long before the API came around.

**Comment by simison** [comment]
Ahh, good idea! We should use that at Trustroots.

**Comment by simison** [comment]
Done (#44) 

(except confirmation stuff, feel free to open a new issue for that if you think it's important)
