### ISSUE TITLE
Other domains

### ISSUE THREAD

**Issue by simison** [hackercouch/hackercouch#39]
FYI, I just registered [hackercouch.org](http://www.hackercouch.org) and [hackercouch.net](http://www.hackercouch.net) and 301 redirected them to here.

Take it as a donation. ;-)

If anyone wants access to domain control, let me know your [NameCheap](https://www.namecheap.com/) email or username here or write me mikael@ihminen.org

**Comment by ppaeps** [comment]
Cool! :-)

**Comment by captn3m0** [comment]
Thanks!
