### ISSUE TITLE
Add Gravatar

### ISSUE THREAD

**Issue by simison** [hackercouch/hackercouch#40]
- Design discussion about Gravatars #7
- Duplicate of #32 but that thread sorta went to many directions, let's keep this purely on discussing tech solution for Gravatars.

---

Seems like there are two ways to go:
- Generate Gravatar hash at the client using https://github.com/webmodules/gravatar
- Use a plugin and compile the site before deployment using a rake task: http://blog.sorryapp.com/blogging-with-jekyll/2014/02/13/add-author-gravatars-to-your-jekyll-site.html

I'd go with the latter. Thoughts?

**Comment by captn3m0** [comment]
Liquid has a `md5` hash filter: https://docs.shopify.com/themes/liquid-documentation/filters/string-filters#md5 used mostly for gravatars

**Comment by simison** [comment]
Cool, that makes it pretty easy, then!

**Comment by simison** [comment]
As it turns out https://github.com/captn3m0/hackercouch/pull/48#issuecomment-160916473:

> So, the liquid gem doesn't support md5: https://github.com/jekyll/jekyll/issues/2491. Shopify's internal version does.

**Comment by simison** [comment]
Started working on this here: https://github.com/captn3m0/hackercouch/tree/gravatar — but won't have time for some two days now. Feel free to continue with this!

**Comment by simison** [comment]
@jancborchardt commented (https://github.com/captn3m0/hackercouch/issues/59#issue-120310806):

> Now I know that we shouldn’t reduce people to their looks, but profile pictures just help to quickly relate to people and also remember them.
> 
> We could simply get that info from the person’s Github profile (just like we can get the location btw).

**Comment by captn3m0** [comment]
Closing this, as now we have gravatars on the website.

**Comment by jancborchardt** [comment]
@captn3m0 can we add them in the list on the homepage as well? Every occurence of a nickname / name should have the relevant avatar left next to them.

**Comment by captn3m0** [comment]
I make no promises on how ugly/good it will look, but I'll get to it. Will also replace the nicks on homepage with names.

**Comment by simison** [comment]
We'll have them on front page with the new layout, not worth putting effort on this unless new layout gets delayed, say, more than week.

From #7: https://projects.invisionapp.com/share/SV57AUYAH#/screens/120919514

**Comment by captn3m0** [comment]
Cool then. Will work on an API client instead, then.

**Comment by simison** [comment]
I'd appreciate getting Fontello working as well! :-) (#25)
