### ISSUE TITLE
Faster edits via third-party hosting

### ISSUE THREAD

**Issue by captn3m0** [hackercouch/hackercouch#47]
Discussed on #42 previously. Thought I'd create a new issue.

Current idea is to have a `gist: id` field that is embedded in the HTML via JS.

**Comment by ppaeps** [comment]
As I pointed out in #42: I wonder if this is really a problem we need to 
fix?

If a couch is going to be unavailable for a longer period of time `git 
rm` feels like the right thing to do.  It's very easy to revert when the 
couch becomes available again.

I also worry about the privacy implications of making it too easy to 
express real-time couch availability.  I think it's a fine idea to 
annotate couches with _references_ or _experiences_, but if we make it 
too easy to indicate a couch is being surfed (and presumably by whom), 
this becomes yet another way of tracking people around the world.

Maybe I'm too paranoid though.

## 

Philip Paeps
Senior Reality Engineer
Ministry of Information

**Comment by captn3m0** [comment]
We might face issues we a lot of people hop on to hackercouch and we are not able to handle the  workload. I'm skeptical of using gists or any sort of embeds as well, because of javascript creep, but thought I'd discuss it a bit.

**Comment by captn3m0** [comment]
I'm closing this for now. Don't think there is a need for this
