### ISSUE TITLE
Use jekyll plugins?

### ISSUE THREAD

**Issue by captn3m0** [hackercouch/hackercouch#50]
We are currently hosted on github-pages + Jekyll, where our build is generated by github itself on every push to `gh-pages`. However, we are restricted by this because github-pages doesn't allow custom plugins, except for a few: https://help.github.com/articles/using-jekyll-plugins-with-github-pages/

**Comment by ppaeps** [comment]
I'm happy to donate a jail and address space on a well-connected machine 
with lots of spare bandwidth if this becomes a serious problem.  Are we 
in any immediate risk of running into the limitations of GitHub Pages?

**Comment by captn3m0** [comment]
The restrictions we are facing:
- `liquid`, the template engine we use doesn't support `md5` filters. See #48 
- Hard to support both json and html formats easily on plain Jekyll. A couch can compile to just one format. I am currently thinking of hacking this via symlinks, but if we run our own builds we can push whatever we want.

Another alternative is to keep our data in the `master` branch, and then the build server (travis) does the following:
- Run test
- Build the entire site
- Switch the branch to `gh-pages` and commit the new data
- Pushes the `gh-pages` branch back to GitHub

Since its a complete build, GitHub won't try to build it again and just serve it at hackercouch.com. Slightly more complicated, though.

**Comment by ppaeps** [comment]
> Another alternative is to keep our data in the `master` branch, and 
> then the build server (travis) does the following[...]

I like this idea.  It also feels more "natural" to look for "source 
code" on `master`.  It would also neatly keep everything on GitHub and 
relieve us of the burden of setting up and maintaining other 
infrastructure.  (At least until we run into other walls).

**Comment by captn3m0** [comment]
Sounds good, I'll work on this. Was also thinking of forking liquid and adding the filters there, but not sure if thats a good idea.

**Comment by simison** [comment]
So to implement e.g. search (#7):
1. Would be easier for certain features to have couches loaded via JS. 
2. To do that, would be easier to use json. 
3. It's easier and less error-prone to have users submit their couches as markdown.
4. To build a json-blob out of couches-markdown files, we'll need to process that file before, and thus we can include e.g. md5 hashes directly to the json file (and any other stuff that we might want to generate, e.g. last updated -timestamp).

I'd propose to have a `rake` command to build into a folder and then push _only that folder_ to `gh-pages` branch. Actual development would happen at master branch, where we would _not_ have the json etc files, only `*.md` couch files.

Thoughts?

**Comment by captn3m0** [comment]
Two things:
1. I don't want to add rake since jekyll plugins pretty much allow everything we need (such as md5 and preprocessing)
2. My plan for supporting json was to create a `_couches_json` symlink to the `_couches` directory. Then this becomes a second collection which can use a different layout. This layout will just publish the couch to json

If we need to load all couches to json, that is just a matter of creating a `couches.json` file with the proper preprocessing in it. `{{site.data.couches|json}}` is all that we really need.

**Comment by captn3m0** [comment]
I've pretty much implemented most of this in #56. Only the final bits and pieces for deployment are left, and I'll get to them tomorrow. I'm closing this (since we decided on shifting to plugins), so we can continue the discussion in the PR itself.
