### ISSUE TITLE
Frameworks

### ISSUE THREAD

**Issue by simison** [hackercouch/hackercouch#53]
Some points:
- I want to keep things super simple 
- but at the same time _damn good looking_.
- It's also fun to learn new stuff and this sort of projects are excellent excuses.

Any preference framework to use for the new design (#7)?

Since the layout gives and sentiment to use Material Design and there are two major frameworks to do just that:
- http://www.material-ui.com/ (to use with [React](https://facebook.github.io/react/))
- https://material.angularjs.org/ (to use with [Angular](https://www.angularjs.org/))
- http://mike1234.com/ember-material-design/ (to use with [Ember](http://emberjs.com/))

Personally I'm very experienced with Angular, although I would love to learn more about React.

Any takers to work on new html/css/js? (I can definitely assist, maybe even do the job). I'd say let the most active person working on this to decide on framework, as long as it's something big enough and not some tiny experimental thing. ;-) Another priority would be that if way more people are familiar with framework X than Y, use the X.

**Comment by captn3m0** [comment]
I'd much rather prefer something without JS. I have used [materializecss.com](http://materializecss.com/) [in the past](https://captnemo.in/talks/josd/) and looks pretty neat.

Is there really a need of a javascript framework for a site of this nature?

**Comment by simison** [comment]
I'm not sure how to implement search or sorting (and other possible feats) without.

That said I'm open for completely static pages as well, but would love to hear some arguments first. ;-)

**Comment by captn3m0** [comment]
- I don't think there is a need of sorting, considering we don't really have any way to sort couches. (Atleast till we start taking reviews)
- Search would need javascript for sure. The two alternatives that I am aware of are [lunr.js](http://lunrjs.com/) and [search-index.js](https://github.com/fergiemcdowall/search-index).

But neither of these is complicated enough to actually need a javascript framework, imo.

**Comment by simison** [comment]
Fair enough! :-) Let's go with Materializecss, after a quick look it seems excellent for this size of a project.

**Comment by simison** [comment]
PR #77
