### ISSUE TITLE
Move to an organisation

### ISSUE THREAD

**Issue by simison** [hackercouch/hackercouch#54]
Should we move this to an [organisation](https://help.github.com/articles/creating-a-new-organization-account/)?

Thoughts @captn3m0 @ppaeps @chettyarun @jancborchardt ?

**Comment by captn3m0** [comment]
So far github.com/hackercouch is available. I am completely fine either way, but i think orgs make sense if you plan to have more than 1 repo? Unless we are building an entire ecosystem around hackercouch, this seems a bit overkill to me.

**Comment by simison** [comment]
I'm thinking more in terms of securing continuity and team spirit. It's more of a signal rather than pragmatic need.

But I have no strong objections either way.

**Comment by jancborchardt** [comment]
I’d agree. Did the same with @libreprojects and @litewrite to not have it so centered around my person.

Just went ahead and created https://github.com/hackercouch and added you to it. Also started https://twitter.com/hackercouch which I can of course give you the credentials to so we can tweet about developments and retweet couch offers/searches. :)

Especially for the upcoming [Chaos Communication Congress](https://events.ccc.de/congress/2015/wiki/Main_Page) in Hamburg I guess we could put the site in full gear.

**Comment by simison** [comment]
Also, @captn3m0 said at IRC:

> If we are going to have multiple clients, maybe we should think of an org after all

Because of course we _must_ have a terminal CLI. :-D

**Comment by jancborchardt** [comment]
Now, if we want to move to the org, @captn3m0 you just have to move the repo. All issues etc will be kept and you are also owner of the org along with @simison @ppaeps and me. We can add more collaborators etc – I always like to be liberal there so we don’t have bottlenecks and push stuff forward.

**Comment by ppaeps** [comment]
> Because of course we _must_ have a terminal CLI. :-D

Yes!  We must!  I've been hacking on one in the background but I got 
distracted this week.  I'll push a work in progress somewhere.  Perhaps 
to the new orga. ;-)

**Comment by captn3m0** [comment]
I'll move the repo as soon as I reach my laptop.

@ppaeps: The plugins branch serves json. Building a cli would be easy for
that.

@jancborchardt tweetdeck supports giving account access without sharing
credentials. Just login with hackercouch and give @captn3m0 admin access.

**Comment by simison** [comment]
everyone; awesome!

+1 for tweetDeck.

**Comment by captn3m0** [comment]
Closing this, since we have moved now :+1:

Need to make a few changes on the site + README, but I'll take care of that.

**Comment by jancborchardt** [comment]
Yeah, nice! :) Best part about this is we get to advertise the project on our profile page! @simison set your visibility from Private to Public on https://github.com/orgs/hackercouch/people ;)

@simison if you have Tweetdeck, can you give account access to @captn3m0?

**Comment by simison** [comment]
Added @jancborchardt and @captn3m0 to TweetDeck. Anyone else how needs access, lemme know your Twitter handle.

**Comment by captn3m0** [comment]
@simison The twitter.com/hackercouch account has been suspended right now (along with every other account I had access to via Tweetdeck). Can you check and file an appeal at https://help.twitter.com/forms/general?subtopic=suspended please?

**Comment by simison** [comment]
@captn3m0 looking! 👍
