### ISSUE TITLE
Spread!

### ISSUE THREAD

**Issue by simison** [hackercouch/hackercouch#57]
Let's collect a list of blogs / zines / other stuff where we can spread this once the new design is out (#7).
### Zines
- https://gigaom.com
- http://www.theverge.com
- http://www.dailydot.com
- http://kernelmag.dailydot.com
- http://www.vice.com
- http://www.wired.com
- https://www.wired.de
- https://news.ycombinator.com
- http://techcrunch.com
- http://arstechnica.com
- http://www.hybe.com
- https://www.theinformation.com
### Blogs
- http://framablog.org/ (in French)

**Comment by captn3m0** [comment]
This is a bit too much for me, and I think I'll let you handle these bits
Don't really expect/want it to become too big.

**Comment by jancborchardt** [comment]
Yeah, I would also be a bit cautious of too actively promoting this. It’s an even smaller circle than Trustroots, and just overflowing it might be a bit much in the beginning?

**Comment by simison** [comment]
Yeah you're probably right, organic is good.

FYI:
https://twitter.com/alebaffa/status/672895272423456768
https://www.producthunt.com/tech/hackercouch
