### ISSUE TITLE
Migrate to Jekyll v3

### ISSUE THREAD

**Issue by simison** [hackercouch/hackercouch#89]
https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
https://jekyllrb.com/news/2015/10/26/jekyll-3-0-released/

It mostly works but with some bugs.
- [ ] Fix excerpts
- what else?

**Comment by simison** [comment]
FYI 
- https://github.com/blog/2220-github-pages-to-upgrade-to-jekyll-3-2
- https://github.com/blog/2236-github-pages-now-runs-jekyll-3-2

**Comment by captn3m0** [comment]
Strikethroughs are broken as of now, because we get kramdown `1.9.x` while GFM strikethroughs were fixed in the 1.10.0 release: https://github.com/gettalong/kramdown/pull/307

Noted at https://hackercouch.com/couches/harman.html thanks to @harman28 

Jekyll upgrade should fix this automatically.

**Comment by captn3m0** [comment]
Looks like we have kramdown pinned to `~>1.9` in the Gemfile. Attempting an upgrade :+1:

**Comment by simison** [comment]
Done at https://github.com/hackercouch/hackercouch/pull/149 

Kudos to @captn3m0 !
