### ISSUE TITLE
Do something about htmlproof link errors

### ISSUE THREAD

**Issue by simison** [hackercouch/hackercouch#92]
```
- ./_site/couches/tonocm.html
  *  External link http://hcardenas.com/ failed: 500 No error
- ./_site/related.html
  *  External link http://www.adoptahacker.com/ failed: 523 No error
htmlproof 2.5.2 | Error:  HTML-Proofer found 2 failures!
```

https://travis-ci.org/hackercouch/hackercouch/builds/111392333

via https://github.com/hackercouch/hackercouch/pull/91

**Comment by chaitanyanettem** [comment]
Those two websites seem to be down. (http://hcardenas.com/ & http://www.adoptahacker.com/)

The first is listed as someone's website in their [couch](https://github.com/hackercouch/hackercouch/blob/master/_couches/tonocm.md). The second is in the related websites section.

One possible solution might be to catch HTML-Proofer exceptions and show a logo next to the URLs linked in the couches which indicate that they are down.

**Comment by captn3m0** [comment]
Pushed a fix for the same. I like the htmlproofer suggestion. Another thing I did recently was setup http://nightli.es/ for hackercouch, which means we run builds every day now. So any build errors will be caught as soon as they happen rather than on the next PR.

**Comment by captn3m0** [comment]
Marking this as closed for now.

**Comment by simison** [comment]
Good solution @captn3m0, thanks!
